version: '2'
services:
  nginx:
    image: nginx
    command: sh -c "sed -ri 's/user[[:space:]]+nginx/user www-data www-data/g' /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    restart: always
    volumes:
      - ./data/certs/${DOMAIN}/fullchain.pem:/etc/nginx/fullchain.pem:ro
      - ./data/certs/${DOMAIN}/privkey.pem:/etc/nginx/privkey.pem:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/letsencrypt.conf:/etc/nginx/letsencrypt.conf:ro
      - ./data/logs/nginx:/var/log/nginx
      - ./data/pydio:/srv/www
      - ./data/php:/php
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  php:
    build: ./php
    volumes:
      - ./data/run/mysqld:/run/mysqld
      - ./data/pydio:/srv/www
      - ./data/php:/php
    dns:
      - 8.8.8.8
      - 8.8.4.4

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: 'pydio'
      MYSQL_USER: 'pydio'
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/run/mysqld:/run/mysqld
    dns:
      - 8.8.8.8
      - 8.8.4.4

  letsencrypt:
    build: letsencrypt
    command: --domain ${DOMAIN}
    environment: 
      - CF_EMAIL=${CF_EMAIL}
      - CF_KEY=${CF_KEY}
      - CF_DEBUG=true
      - CF_DNS_SERVERS='8.8.8.8 8.8.4.4'
    volumes: 
      - ./data/certs:/dehydrated/certs
      - ./data/letsencrypt/accounts:/dehydrated/accounts
      - ./letsencrypt/config:/dehydrated/config:ro
    dns:
      - 8.8.8.8
      - 8.8.4.4